version: "3.1"

services:
    db:
        image: mysql:8.4
        container_name: db
        restart: always
        env_file: .env
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wordpress
        restart: always
        env_file: .env
        ports:
            - "${WORDPRESS_PORT}:80"
        volumes:
            - wordpress_data:/var/www/html
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: ${WORDPRESS_DB_HOST}
            PMA_USER: ${WORDPRESS_DB_USER}
            PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD}

volumes:
    wordpress_data:
    db_data:
